version: 2

builds:
  - binary: wtfutil
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64

archives:
  - id: default

homebrew_casks:
  - name: wtfutil
    homepage: 'https://wtfutil.com'
    description: 'The personal information dashboard for your terminal.'
    repository:
      owner: wtfutil
      name: homebrew-wtfutil
    hooks:
      post:
        # This hook is needed until this binary is signed and notarized
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wtfutil"]
          end
  - name: wtfutil
    homepage: 'https://wtfutil.com'
    description: 'The personal information dashboard for your terminal.'
    repository:
      owner: linodians
      name: homebrew-tap
    hooks:
      post:
        # This hook is needed until this binary is signed and notarized
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wtfutil"]
          end

announce:
  mastodon:
    enabled: true
    server: "https://social.linodians.com"
  bluesky:
    enabled: true
    username: "wtfutil.bsky.social"
